### ISSUE TITLE
Add trivial command line executables?

### ISSUE THREAD

**Issue by kindaro** [haskell-hvr/HsYAML-aeson#3]
I thought it would be nice to have programs in the `x2y` style, for converting between Yaml & Json, at hand. So I wrote them. See kindaro/HsYAML-aeson@efd4507.

Can we put them in this package? Or rather, what you advise me to do with them?

**Comment by vijayphoenix** [comment]
Yeah, sure. 
Please make a PR for the same.

**Comment by kindaro** [comment]
@vijayphoenix I made a pull request. Please take a look and comment.

**Comment by vijayphoenix** [comment]
Closed by #4
